# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30dc2f1d4d762ce2b0e7c86bc446528e0b7d7bda9dd8b4bc3a557e52a4da577b469ecb304461b3a0c628da1ade30c041aef1f4a4d861c5c9317d8335af432bb5

test:
  secret_key_base: d709525bf95a4929d1f4be88ec06a2ed38a81b574e6c2d8bc3a1ebb980c8b488817c04f430c47654d9bde25372ae5f6c336c8bed6af32903490cf419897471a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
